### ISSUE TITLE
String manipulation

### ISSUE THREAD

**Issue by intoinside** [c128lib/framework#6]
Some string manipulation macros can be added:

- [x] StringLength()
- [x] StringCopy()
- [x] StringCopyLeft() - This is string copy but length specified
- [x] StringCopyRight() - This is string copy but length specified from end
- [x] StringCopyMid() - This is like get substring
- [x] StringConcatenate()
- [x] StringCompare()
Better talking names should be used.

https://codebase64.org/doku.php?id=base:string_manipulation_routines&s[]=string&s[]=manipulation

Test:
- [x] StringLength()
- [x] StringCopy()
- [x] StringCopyLeft() - This is string copy but length specified
- [x] StringCopyRight() - This is string copy but length specified from end
- [x] StringCopyMid() - This is like get substring
- [x] StringConcatenate()
- [x] StringCompare()

**Comment by johnpalermo** [comment]
Should we have also:
1) string delete - delete a substring from a string
2) string insert - insert a substring into a string
3) string compare - compare 2 strings
4) get substring - get substring from a string
5) find substring - find the position of a substring

**Comment by johnpalermo** [comment]
I could work on some of these if needed.  That would be a fun thing to work on.

**Comment by intoinside** [comment]
Yes of course, i'll work on quicksort

Il mar 7 feb 2023, 15:53 John Palermo ***@***.***> ha scritto:

**Comment by johnpalermo** [comment]
> Some string manipulation macros can be added:
> 
> * [x]  strlen
> * [x]  strcpy
> * [x]  strncpy (like previous but len is specified)
> * [x]  strcat
>   Better talking names should be used.
> 
> [https://codebase64.org/doku.php?id=base:string_manipulation_routines&s[]=string&s[]=manipulation](https://codebase64.org/doku.php?id=base:string_manipulation_routines&s%5B%5D=string&s%5B%5D=manipulation)

Macro names for consideration:

- [x] StringLength()
- [x] StringCopy()
- [x] StringCopyLeft() - This is string copy but length specified
- [x] StringCopyRight() - This is string copy but length specified from end
- [x] StringCopyMid() - This is like get substring
- [x] StringConcatenate()
- [x] StringCompare()

**Comment by johnpalermo** [comment]
Edited main comment to use better English names and include some new macros also. Some tasks completed as well, but not tested yet.  Testing is next.

**Comment by johnpalermo** [comment]
Removing StringFind() from this issue.  Will create a new issue for StringFind(), to be worked on with more time.  I think this is a good first version of the string library.  More can be added later, with more time.

**Comment by intoinside** [comment]
Good work!

**Comment by johnpalermo** [comment]
Thank you.
